# Enhanced Dependabot configuration for comprehensive dependency management
version: 2

# GitHub Actions dependencies
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Security: Pin to specific commit SHAs
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    # Security: Group related updates
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security: Require approval for major updates
    reviewers:
      - "fraware"
    assignees:
      - "fraware"
    # Security: Limit to security updates only
    open-pull-requests-limit: 10
    # Security: Auto-merge security patches
    auto-merge:
      when:
        dependency-type: "direct"
        update-type: "patch"

# Ruby dependencies (Jekyll site)
  - package-ecosystem: "bundler"
    directory: "/home_page"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Security: Group all Ruby updates
    groups:
      ruby-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security: Require approval for major updates
    reviewers:
      - "fraware"
    assignees:
      - "fraware"
    # Security: Auto-merge security patches
    auto-merge:
      when:
        dependency-type: "direct"
        update-type: "patch"
    # Security: Limit to security updates only
    open-pull-requests-limit: 5
    # Security: Update vulnerable dependencies immediately
    ignore:
      # Don't ignore security updates
      - dependency-name: "*"
        update-types:
          - "security"

# Python dependencies (if any)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Security: Group Python updates
    groups:
      python-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security: Require approval for major updates
    reviewers:
      - "fraware"
    assignees:
      - "fraware"
    # Security: Auto-merge security patches
    auto-merge:
      when:
        dependency-type: "direct"
        update-type: "patch"
    # Security: Limit to security updates only
    open-pull-requests-limit: 5

# Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Security: Group Docker updates
    groups:
      docker-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security: Require approval for major updates
    reviewers:
      - "fraware"
    assignees:
      - "fraware"
    # Security: Auto-merge security patches
    auto-merge:
      when:
        dependency-type: "direct"
        update-type: "patch"
    # Security: Limit to security updates only
    open-pull-requests-limit: 5

# npm dependencies (if any JavaScript tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Security: Group npm updates
    groups:
      npm-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Security: Require approval for major updates
    reviewers:
      - "fraware"
    assignees:
      - "fraware"
    # Security: Auto-merge security patches
    auto-merge:
      when:
        dependency-type: "direct"
        update-type: "patch"
    # Security: Limit to security updates only
    open-pull-requests-limit: 5

# Security: Global settings for all ecosystems
global:
  # Security: Require approval for major updates
  reviewers:
    - "fraware"
  assignees:
    - "fraware"
  # Security: Auto-merge security patches
  auto-merge:
    when:
      dependency-type: "direct"
      update-type: "patch"
  # Security: Limit to security updates only
  open-pull-requests-limit: 25
  # Security: Update vulnerable dependencies immediately
  ignore:
    # Don't ignore security updates
    - dependency-name: "*"
      update-types:
        - "security"
  # Security: Require status checks to pass
  required-status_checks:
    - "ci"
    - "security-scan"
    - "dependency-check"
